import React from "react";
import { Alert } from "react-bootstrap";
import WorkflowDiagram from "../../components/workflow/WorkflowDiagram";
import { useAppContext } from "../../context/AppContext";

export default function Workflow() {
  const { result } = useAppContext();

  if (!result) {
    return <Alert variant="info">Generate a workflow from the Home page first.</Alert>;
  }

  return (
    <div className="d-flex flex-column align-items-center">
      <h2 className="mb-3 text-center">Workflow architecture</h2>
      <p className="text-muted text-center">
        Generated by {result.best_model}, overall score {result.overall_score}
      </p>
      <div className="w-100 d-flex justify-content-center">
        <WorkflowDiagram workflowJson={result.workflow_json} diagramPath={result.diagram_path} />
      </div>
    </div>
  );
}
